song_name = ['Good Life', 'I Want You To Know', 'Lose You To Love Me', 'Love Runs Out', 'Alright', 'WAP', 'Ceiling Games', 'Moana', 'Hanuman Chalisa', 'Sleepover', 'Take Me To Church', 'You Are The Reason', 'Playing Townes', 'Sick Boy', 'Everybody Dies In Their Nightmares', 'Lonely Together', 'Girls Like You', 'Want It Kept', 'Bleeding Love', 'Jolene!', 'Titans', 'Apricots', 'Heat Waves', 'i hate u i love u', 'Photograph', 'Shayad', 'Memories', 'Moon Rider', 'Overdrive', 'The Way You Felt', 'Dandelions', 'Send Me An Angel', 'Love Yourself', 'Not Afraid', 'Alive', 'Closer', 'Party Girl', 'Hold It Against Me', 'Surrender', 'All Time Low', 'All Night', 'Soldier', 'Tere Sang Yaara', 'LET IT GO', 'Tory lanez freestyle', 'Boyfriend', 'I Get You', 'No Promises', 'Selfish Love', 'The Imitation Game', 'Rare', 'telepatía', 'I Need Some Sleep', 'I Want It That Way', 'Speechless', 'You & I', 'Talk', 'When We Were Young', 'She', 'Returning To Methuen', 'Glad You Came', 'Believe What I Say', 'Summer Thing', 'Cloudy Day', 'Rescue Me', 'All I Want', 'Phantoms and Friends', 'Try', 'SugarCrash!', 'Daddy Issues', 'Break My Heart Myself', 'Baila Conmigo', 'Mine', 'No Lie', 'Ophelia', 'Switch It Up', 'I Would Like', 'SOS', 'Woman Like Me', 'Just the Way You Are', 'u love u', 'I Won', 'ME!', 'Anxiety', 'Disrespectful', 'Bright Eyes', 'The One I Love', 'Solar Power', 'Jealous', 'Reasons', 'Unconditionally', 'Overwhelmed', 'Let You Down', 'You And Me', 'Legends', 'Malang', 'Sweet but Psycho', 'Rumors', 'Someone To Stay', 'Brush Fire']
artist_name = ['Billie Eilish', 'Joel Corry', 'Gryffin', 'Carlos Rafael Rivera', 'Ariana Grande', 'Ludovico Einaudi', 'Alan Walker', 'Jonas Blue', 'Ed Sheeran', 'Imagine Dragons', 'The Chainsmokers', 'Jax Jones', 'Ellie Goulding', 'Olivia Rodrigo', 'Conan Gray', 'Stateless', 'Amy Winehouse', 'Taylor Swift', 'Empire of the Sun', 'Big Sean', 'Pop Smoke', 'Christina Perri', 'Juice WRLD', 'Maroon 5', 'The Local Train', 'William Black', 'Ryan Mack', 'Calvin Harris', 'Romy', 'Armaan Malik', 'blackbear', 'Klaas', 'Selena Gomez', 'Macklemore & Ryan Lewis', 'The Cranberries', 'Joshua Burnside', 'Charlie Puth', 'WILDES', 'Ali Gatie', '42 Dugg', 'Sam Feldt', 'glaive', 'Kanye West', 'Lee DeWyze', 'Zodiac Wave', 'Nelly Furtado', 'Marshmello', 'Roy Jones Jr.', 'Eminem', 'One Direction', 'Jaden Thompson', 'Dua Lipa', 'Zedd', 'Kelly Clarkson', 'Ankur Tewari', 'Pitbull', 'joan', 'Trevor Daniel', 'Sleepy Hallow', 'Prateek Kuhad', 'SLANDER', 'Picture This', 'Enrique Iglesias', 'jxdn', 'KC Lights', 'Logic', 'Clinton Kane', 'vaultboy', 'Tyga', 'Tom Odell', 'Martin Jensen', 'ZAYN', 'MAX', 'Kina', 'Fall Out Boy', 'Camila Cabello', 'Lewis Capaldi', 'LOLO', 'FLETCHER', 'Kevin Gates', 'Ava Max', 'Young Money', 'Art Garfunkel', 'JD McPherson', 'Duncan Laurence', 'Secondcity', 'Yellow Claw', 'Yves V', 'Louis The Child', 'Tones And I', 'Trippie Redd', 'Sia', 'Internet Money', 'Kelli-Leigh', 'Jay Gwuapo', 'Bebe Rexha', '44phantom', 'Yann Tiersen', 'Rihanna', 'The Vamps']
# Asks the user to enter a number of a  song
position = int(input("Enter a number representing the position of a song in the chart: "))
indexVal = position - 1
# Checks the position range
if position >= 1 and position <= 100:
  print("The song title is " + str(song_name[indexVal]) + " and " + "artist is " + str(artist_name[indexVal]))
  # Checks the song's position
  if position <= 10:
     print("The song is in Top 10")
  elif position <= 50:
     print("The song is in the Top 50")
  elif position <= 100:
    print("The song is in the Top 100")
    
else: print("Invalid position! Please enter a number between 1 and 100")
